class UserAlreadyExistsError(Exception):
    pass


class InternalServerError(Exception):
    pass
